# Generated by Django 4.2.2 on 2023-06-19 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_note', models.TextField()),
                ('note_private', models.BooleanField(default=False)),
                ('note_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_status', models.CharField(choices=[('R', 'read'), ('RD', 'reading'), ('WR', 'want_to_read')], default='WR')),
                ('book_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryAPI.note')),
                ('library_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryAPI.book')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='related_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryAPI.book'),
        ),
    ]
